name: Build wasm version and deploy to github pages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**.zig'
      - '.github/workflows/wasm-deploy.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zig-version: ["0.13.0"]

    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Setup emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      - name: Build, prepare to deploy
        run: |
          zig build -Dtarget=wasm32-emscripten --sysroot emsdk/upstream/emscripten
          touch zig-out/htmlout/.nojekyll

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          folder: zig-out/htmlout
          single-commit: true
