name: zig build test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.zig'
      - '.github/workflows/zig-build-test.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - '**.zig'
      - '.github/workflows/zig-build-test.yml'

  schedule:
    - cron: "0 0 * * Sat"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zig-version: 
          - "0.14.1"
          # - "mach-latest"
          # - "master"
    
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check formatting
        run: zig fmt --check .

      - name: Install and run zlint
        run: |
          curl -fsSL https://github.com/DonIsaac/zlint/releases/download/v0.7.6/zlint-linux-x86_64 > zlint
          chmod +x zlint
          ./zlint --deny-warnings

      - run: zig build test -- noraylib
